version: '3.7'
services:
  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql
      - ./init-files:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=DB_URL
      - MYSQL_USER=DB_USER
      - MYSQL_PASSWORD=DB_PASS